// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    var ARRCookies, CRTG_COOKIENAME, CRTG_NID, CRTG_URI, CRTG_VARNAME, appendTag, criteoScript, criteoUrl, crtgGetCookie, getCriteo, scriptTag;
    ARRCookies = document.cookie.split(';');
    CRTG_NID = '1842';
    CRTG_VARNAME = 'crtg_content';
    CRTG_COOKIENAME = 'cto_trulia';
    CRTG_URI = "" + window.location.protocol + "//rtax.criteo.com/delivery/rta/rta.js";
    crtgGetCookie = function() {
      var i, x, y;
      x = y = void 0;
      i = 0;
      while (i < ARRCookies.length) {
        x = ARRCookies[i].substr(0, ARRCookies[i].indexOf('='));
        y = ARRCookies[i].substr(ARRCookies[i].indexOf('=') + 1);
        x = x.replace(/^\s+|\s+$/g, '');
        if (x === CRTG_COOKIENAME) {
          return unescape(y);
        }
        i++;
      }
      return '';
    };
    criteoScript = function() {
      window.crtg_content = crtgGetCookie();
      return appendTag(scriptTag());
    };
    scriptTag = function() {
      var crtg_script;
      crtg_script = document.createElement('script');
      crtg_script.type = 'text/javascript';
      crtg_script.src = criteoUrl();
      crtg_script.async = true;
      return crtg_script;
    };
    criteoUrl = function() {
      var crtg_url;
      crtg_url = "" + CRTG_URI + "?netId=" + CRTG_NID;
      crtg_url += "&cookieName=" + CRTG_COOKIENAME;
      crtg_url += "&varName" + CRTG_VARNAME;
      return crtg_url;
    };
    appendTag = function(script) {
      if (document.getElementsByTagName('head').length > 0) {
        return document.getElementsByTagName('head')[0].appendChild(script);
      } else if (document.getElementsByTagName('body').length > 0) {
        return document.getElementsByTagName('body')[0].appendChild(script);
      }
    };
    getCriteo = function() {
      return $.Deferred(function(deferredObj) {
        criteoScript();
        return deferredObj.resolve();
      }).promise();
    };
    return {
      init: getCriteo
    };
  });

}).call(this);
