// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    var ARRCookies, criteo, crtg_getCookie, getCriteo;
    ARRCookies = document.cookie.split(';');
    crtg_getCookie = function(c_name) {
      var i, x, y;
      x = y = void 0;
      i = 0;
      while (i < ARRCookies.length) {
        x = ARRCookies[i].substr(0, ARRCookies[i].indexOf('='));
        y = ARRCookies[i].substr(ARRCookies[i].indexOf('=') + 1);
        x = x.replace(/^\s+|\s+$/g, '');
        if (x === c_name) {
          return unescape(y);
        }
        i++;
      }
      return '';
    };
    criteo = function() {
      var crtg_cookiename, crtg_nid, crtg_rnd, crtg_script, crtg_url, crtg_varname;
      crtg_nid = '1842';
      crtg_cookiename = 'cto_trulia';
      crtg_varname = 'crtg_content';
      window.crtg_content = crtg_getCookie(crtg_cookiename);
      crtg_rnd = Math.floor(Math.random() * 99999999999);
      crtg_url = location.protocol + '//rtax.criteo.com/delivery/rta/rta.js?netId=' + escape(crtg_nid);
      crtg_url += '&cookieName=' + escape(crtg_cookiename);
      crtg_url += '&rnd=' + crtg_rnd;
      crtg_url += '&varName=' + escape(crtg_varname);
      crtg_script = document.createElement('script');
      crtg_script.type = 'text/javascript';
      crtg_script.src = crtg_url;
      crtg_script.async = true;
      if (document.getElementsByTagName('head').length > 0) {
        return document.getElementsByTagName('head')[0].appendChild(crtg_script);
      } else {
        if (document.getElementsByTagName('body').length > 0) {
          return document.getElementsByTagName('body')[0].appendChild(crtg_script);
        }
      }
    };
    getCriteo = function() {
      return $.Deferred(function(deferred_obj) {
        criteo();
        return deferred_obj.resolve();
      }).promise();
    };
    return {
      init: getCriteo
    };
  });

}).call(this);
